networks:
  portfolio-management-network:
    driver: bridge
services:
  flyway-migrate:
    image: flyway/flyway:10-alpine
    command: migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    environment:
      - FLYWAY_URL=jdbc:mysql://portfolio-db:3306/portfolio
      - FLYWAY_USER=${MYSQL_USER:-user}
      - FLYWAY_PASSWORD=${MYSQL_PASSWORD:-password}
    depends_on:
      portfolio-db:
        condition: service_healthy
    networks:
      - portfolio-management-network
  portfolio-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-management-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      timeout: 20s
      retries: 10
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - portfolio-management-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mysql_data:
  minio_data:
