networks:
  portfolio-management-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    image: DOCKER_USER/portfolio-management-networkporfolio-management-frontend:TAG
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - user-service
    environment:
      - APP_URL=${APP_URL:-http://${VM_HOST:-localhost}:3000}
      - AUTH_URL=${AUTH_URL:-http://${VM_HOST:-localhost}:8082}
      - USER_URL=${USER_URL:-http://${VM_HOST:-localhost}:8083}
    networks:
      - portfolio-management-network

  auth-service:
    build: ./auth-service
    image: DOCKER_USER/portfolio-management-auth-service:TAG
    ports:
      - "8082:8082"
    depends_on:
      flyway-migrate:
        condition: service_completed_successfully
    environment:
      - spring.datasource.url=jdbc:mysql://portfolio-db:3306/portfolio
      - spring.datasource.username=${MYSQL_USER:-user}
      - spring.datasource.password=${MYSQL_PASSWORD:-password}
      - JWT_SECRET=${JWT_SECRET:-bXlWZXJ5U2VjcmV0S2V5VGhhdElzMzJDaGFyc0xvbmcxMjM0NTY3ODlBQkM=}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-3600000}
      - APP_URL=${APP_URL:-http://${VM_HOST:-localhost}:3000}
      - frontend.url=${APP_URL:-http://${VM_HOST:-localhost}:3000}
      - frontend.external.url=${APP_URL:-http://${VM_HOST:-localhost}:3000}
      - email.service.url=http://email-service:8081
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-yourClientID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-yourClientSecret}
    networks:
      - portfolio-management-network

  user-service:
    build: ./user-service
    image: DOCKER_USER/portfolio-management-user-service:TAG
    ports:
      - "8083:8083"
    depends_on:
      flyway-migrate:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://portfolio-db:3306/portfolio
      - spring.datasource.username=${MYSQL_USER:-user}
      - spring.datasource.password=${MYSQL_PASSWORD:-password}
      - JWT_SECRET=${JWT_SECRET:-bXlWZXJ5U2VjcmV0S2V5VGhhdElzMzJDaGFyc0xvbmcxMjM0NTY3ODlBQkM=}
      - MINIO_URL=http://minio:9000
      - MINIO_PUBLIC_URL=http://${VM_HOST:-localhost}:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - APP_URL=${APP_URL:-http://${VM_HOST:-localhost}:3000}
    networks:
      - portfolio-management-network

  email-service:
    build: ./email-service
    image: DOCKER_USER/porfolio-management-email-service:TAG
    ports:
      - "3002:8081"
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD:-emailpassword}
    networks:
      - portfolio-management-network

  flyway-migrate:
    image: flyway/flyway:10-alpine
    command: migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    environment:
      - FLYWAY_URL=jdbc:mysql://portfolio-db:3306/portfolio
      - FLYWAY_USER=${MYSQL_USER:-user}
      - FLYWAY_PASSWORD=${MYSQL_PASSWORD:-password}
    depends_on:
      portfolio-db:
        condition: service_healthy
    networks:
      - portfolio-management-network

  portfolio-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-management-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      timeout: 20s
      retries: 10

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - portfolio-management-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mysql_data:
  minio_data:
