apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-management-mysql-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ngoctu/project/mysql-data
  persistentVolumeReclaimPolicy: Retain