apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-management-mysql-pvc
  namespace: portfolio-management
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: portfolio-management-mysql-pv