apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: portfolio-management-mysql-statefulset
  namespace: portfolio-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-management-mysql
  template:
    metadata:
      labels:
        app: portfolio-management-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-management-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: portfolio
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio-management-mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-management-mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: portfolio-management-mysql-pvc