apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: portfolio-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: DOCKER_USER/portfolio-management-auth-service:TAG
          ports: 
            - containerPort: 8082
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://mysql-host:3307/portfolio
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: JWT_EXPIRATION
              value: "300000"
            - name: JWT_REFRESH_EXPIRATION
              value: "604800000"
            - name: APP_URL
              value: https://nationally-premium-bonefish.ngrok-free.app
            - name: email.service.url
              value: http://email-service:8081
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-secret